# Generated by Django 2.1.2 on 2018-10-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noname', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.IntegerField(choices=[(1, 'Jedzenie dom'), (2, 'Jedzenie na mieście'), (3, 'Jedzenie w pracy'), (4, 'Alkohol'), (5, 'Czynsz'), (6, 'Woda'), (7, 'Prąd'), (8, 'Gaz'), (9, 'Ogrzewanie'), (10, 'Wywóz śmieci'), (11, 'Naprawy'), (12, 'Wyposażenie'), (13, 'Ubezpieczenie'), (14, 'Paliwo'), (15, 'Naprawa'), (16, 'Wyposażenie'), (17, 'Ubezpieczenie'), (18, 'Bilety'), (19, 'Taxi'), (20, 'Telefon'), (21, 'Telewizja'), (22, 'Internet'), (23, 'Lekarz'), (24, 'Badania'), (25, 'Leki'), (26, 'Ubrania'), (27, 'Buty'), (28, 'Kosmetyki'), (29, 'Chemia domowa'), (30, 'Fryzjer'), (31, 'Art. szkolne'), (32, 'Zajęcia dodatkowe'), (33, 'Szkoła'), (34, 'Gry/zabawki'), (35, 'Opieka nad dziećmi'), (36, 'Sport'), (37, 'Kino/teatr'), (38, 'Koncert'), (39, 'Książki'), (40, 'Prezenty'), (41, 'Oszczędności'), (42, 'Hotel/turystyka'), (43, 'Hobby'), (44, 'Edukacja'), (45, 'Oprogramowanie'), (46, 'Inne')]),
        ),
    ]
