# Generated by Django 2.1.2 on 2018-10-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noname', '0002_auto_20181003_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='income',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
